---
# file: roles/python/taks/main.yml

- name: Install pip
  become: true
  apt:
    name:
      - python3-pip
    state: latest
    install_recommends: no

- name: install boto3, the python aws sdk
  become: true
  pip:
    name: boto3
    executable: pip3

- name: requests, etc
  pip:
    name: 
      - requests
      - python-dotenv
      - textblob
    extra_args: --user --upgrade
    executable: pip3
