AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CreateThumbnail:
    Properties:
      CodeUri: build
      Events:
        CreateThumbnailEvent:
          Properties:
            Bucket:
              Ref: SemanticWils
            Events: s3:ObjectCreated:*
          Type: S3
      Handler: app.lambda_handler
      Policies: AWSLambdaExecute
      Runtime: python3.6
      Environment:
        Variables:
          NLTK_DATA: 2
      Timeout: 60
    Type: AWS::Serverless::Function
  SemanticWils:
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
